### ISSUE TITLE
unable to deploy app from image when image name include special chars

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#371]
STR 
Have a reservation with vm deployed from image app and an ovf file that its name is: Test!@#$%^&_()_'.ovf
direct the app to install the ovf with the special chars
Run deploy command

BIR 
an error appears:
![image](https://cloud.githubusercontent.com/assets/17527106/13554719/54db2ba8-e3b8-11e5-90e6-d333da675f0a.png)

**Comment by alexazarh** [comment]
What error appears?
If the error comes from vCenter than we cant do anything about it...

Best regards,
Alex Azarh

**Comment by alonagetzler** [comment]
error should be improved

**Comment by TomerAdmon** [comment]
@razaba / @alonagetzler - is this error OK?
![image](https://cloud.githubusercontent.com/assets/12639815/14061264/d1d57cd8-f38c-11e5-9f51-4f6910259daf.png)

**Comment by TomerAdmon** [comment]
Moving to Backlog - not critical for 7.0

**Comment by razaba** [comment]
we cannot parse this error, because it has no single structure. to better cope with the error we can catch all of the exceptions and refer the client to the logs...

but I think in the case or in ovf deployment in general, it is very important to show the exceptions for the usability of the the feature
(same for #347)
