### ISSUE TITLE
End-to-end automation

### ISSUE THREAD

**Issue by borismod** [QualiSystems/vCenterShell#41]
As a developer I would like to be able to test the shell with full end-to-end automation including CloudShell, ES that executes command on Python shell and real vCenter.

Acceptance criteria:
1. End-To-End automation test runs as part of CI
2. There is a document on confluence describing how automation works and how to add a new test

**Comment by nahumtimerman** [comment]
Scenarios to automate:
Import package
Deploy VM from app
Connect vlan on deployed app
Power on
Power off

To do:
Destroy VM
Disconnect

**Comment by nahumtimerman** [comment]
Refactoring:
- TestInit & TestCleanup to handle things that always happen (or use proxy) because we always want to cleanup test vms and vlans at the end...
- Better to compose testegator class rather than inherit from it
- Assert on prerequisites should return clear message for debug (in fact, use throw exception rather than assert)
- Use RunProcessThread & verify success using contains on processoutput
- Exceptions instead of assertions when not in test!
- If method returns bool, should return True & False, not True & exception :)
- Function names should generally start from a verb that describes what actions they take
- DeployedApp can hold a pointer to vm rather than having two return values, one by out
- All constants should be in the settings class because maintenance gets annoying
- Vlan to "prepare vlan" method
- Test autoresolve separately and add more tests to autoresolve vlan
- Breakup the checking of vlans / getting vlan data from vcenter to building blocks
- create a gateway like proxy but for vCenter / Vlan / VM
- if still using execute command with xmlrpcgateway, move it to xmlrpcgateway and add tests.

**Comment by nahumtimerman** [comment]
Maintenance:
- there is no use case to modify app after it has been added to reservsation.
- therefore settings should be injected to template in manage before test runs, rather than modified the reservation entity.
