### ISSUE TITLE
Fix messages in vCenter Autoload

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#517]
Description: Could not find the VM Location: aaaaaa
--> Description: Could not find VM Location <XX>

Description: Holdeing net work can not be empty
--> Description: Holding Network cannot be empty

Description: Could not select VM Storage because: too many options
--> Description: VM Storage must be selected

Description: Could not find the VM Storage: datastore1 (1)
--> Description: Could not find VM Storage <XX>

Description: Could not find the VM Cluster: 192.168.42.114
--> Description: Could not find VM Cluster <XX>

Description: VM folder cannot be empty
--> Description: VM Folder cannot be empty

Description: Could not select Default dvSwitch because: too many options
--> Description: Default dvSwitch must be selected

**Comment by TomerAdmon** [comment]
Description: Could not find the VM Location: aaaaaa
--> Description: Could not find VM Location   - VERIFIED

Description: Holdeing net work can not be empty
--> Description: Holding Network cannot be empty - VERIFIED

Description: Could not select VM Storage because: too many options
--> Description: VM Storage must be selected   - VERIFIED

Description: Could not find the VM Storage: datastore1 (1)
--> Description: Could not find VM Storage  - VERIFIED

Description: Could not find the VM Cluster: 192.168.42.114
--> Description: Could not find VM Cluster   - VERIFIED

Description: VM folder cannot be empty
--> Description: VM Folder cannot be empty  - VERIFIED

Description: Could not select Default dvSwitch because: too many options
--> Description: Default dvSwitch must be selected   - VERIFIED
