### ISSUE TITLE
Console output bugs

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#533]
## 1
Remove all brackets from output
 ![image](https://cloud.githubusercontent.com/assets/12639815/13951555/731e5c28-f03a-11e5-88d0-9ab0480159a0.png)

## 2 
Deployed Photon_17981214 Successfully 
Should be changed to: 
[deployedAppName] deployed successfully

## 3 - Setup
Remove lines 1-3:
![image](https://cloud.githubusercontent.com/assets/12639815/13951569/8ac6c7a2-f03a-11e5-871d-e4f9dcf1d546.png)

## 4 - Teardown
Remove: begging..... message
Remove: disconnecting all message

![image](https://cloud.githubusercontent.com/assets/12639815/13951619/e18de106-f03a-11e5-9d35-b50c9411ff17.png)

## 5 - Teardown
Powering off is missing
Was deleted message is missing

![image](https://cloud.githubusercontent.com/assets/12639815/13951619/e18de106-f03a-11e5-9d35-b50c9411ff17.png)

**Comment by alonagetzler** [comment]
stuff that we need to fix:
1.	We can live with the brackets [] around the App and Deployed App names (although this was unintended), but please remove them from anywhere else (around IP address, around whole messages etc.)
2.	No need to say “DeployedAppName deployment started” since you already show this message for the app (“AppName deployment started”)
3.	The “Deployed DeployedAppName Successfully” message should be changed to “DeployedAppName deployed successfully” 
4.	All the messages with “is [xxx]…” should have the “…” at the end of them
5.	What I described in the issue https://github.com/QualiSystems/vCenterShell/issues/427 was about the messages when deployed one app, the Setup and Teardown messages should be a little bit different:
o	Setup:
	Apps deployment started
	Apps are being discovered…
	Connecting all apps…
	Apps are powering on…
	Waiting for apps IP addresses, this may take a while…
	Apps IP addresses are updated
	Apps are installing…
	Apps setup ended successfully
o	Teardown:
	Disconnecting all apps…
	Apps are powering off…
	Apps are being deleted…

**Comment by alexazarh** [comment]
After talking with @alonagetzler with agreed that we will remove the brackets [] in the orchestration and if the app name will have blank spaces than we will wrap it with double quotes, like this:
![image](https://cloud.githubusercontent.com/assets/6730546/14065780/fd05aae6-f43f-11e5-9a95-c1e1a1ae75c0.png)

**Comment by tornizanQ** [comment]
Verified
