### ISSUE TITLE
Teardown: Vm that was added from inventory wouldn't be delete during the teardown

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#609]
STR:
1) deploy an app
2) remove the app from the reservation
3) add the app back
4) teardown the reservation

result:
the vm wasn't deleted and in the log we can see: CloudShell API error 100: Cannot execute 'destroy_vm_only' command on a shared resource. Unshare 'PhotonOs1_8111b1f7' and try again.

**Comment by alonagetzler** [comment]
i'm not sure that's a bug, if you kept an app in the inventory (by removing it from the reservation) and then added it to another reservation we don't need to delete it on teardown. if you added it to the same reservation it was created we should delete it on teardown, but that's a really edge case and not a priority.

**Comment by TomerAdmon** [comment]
I can't disagree more.... what you see here is a bug. if you want to keep the machine there even when a setup runs on it, you need to add it to the code.... 
currently we can't tell if a machine was "born" in the reservation or not....

**Comment by alonagetzler** [comment]
to sum it up - the bug is misleading. we have a missing FEATURE which is keeping the reservation ID in which the app was created on the deployed app, and by that allow the orchestration differentiate between apps created in this reservation or in a different one. Until then, if a user wants to refrain from deleting certain apps he can do one of the following  - (1) disable the auto-delete, (2) use this "back door bug" that the teardown process can't delete Shared deployed apps, (3) add an attribute to the deployed app with the reservation ID in which it was created and populate it somehow.

The BUG here is the fact that the teardown process doesn't delete Shared deployed apps, and it isn't high priority. The GAP here is that once we fix this bug we actually delete at teardown both apps deployed within the reservation and apps from the inventory, unless we disable the auto-delete.

**Comment by alexazarh** [comment]
There are 2 options to solve this bug:
1) We can add the tag "allow_shared" to this specific command in the vCenterShell driver. But this means that you can delete the app from another reservation (not the one it was deployed in).
2) We can turn on the option "Locked By Default" for the generic App family and then the resource will be added as exclusive. But this means that you cant use the same deployed app in more than one reservation at the same time.

I personally would go with option #2. 
@alonagetzler / @doppleware  - what do you think?

**Comment by alonagetzler** [comment]
we should go with option 2 (make the default app family Locked By Default)
this should be for 7.0 GA

**Comment by doppleware** [comment]
Lets implement the following behavior:
1. Add three new properties to any resource: created_by_user, created_by_reservation and created_by_domain. These values should be taken from the active execution instance when the resource was created. If the resource was created in a reservation, we need to take that info from the reservation (owner, domain, reservation_id)
1b. Get reservation details should return these details as well in the resource xml (not the matrix in studio etc.)
2. Ask Assaf to add these fields to elastic
3. The teardown procedure should only delete/power off VMs that were created in that sandbox.
4. Change lock by default to true for generic deployed app.
5. Try to bribe Liron to add a checkbox to filter this in the resource search pane... (talk to Meni)

**Comment by alexazarh** [comment]
For 7.0 GA - we will only turn on the option "Locked By Default" for the generic App family
