### ISSUE TITLE
Remove "auto delete" and "auto power off" behavior from vCenter shell

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#756]
there no need for it after the delete refactor. the teadown should always delete VMs created in the reservation, and shouldn't delete VMs created outside the reservation (another reservation or loaded in inventory) regardless of the attribute "auto delete" and "auto power off". the manual deletion done by the "remove" button already ignores the "auto delete" behavior.
- remove logic from teardown
- remove attributes from vCenter (and AWS?)
- remove the attribute from the deploy result (custom params)

**Comment by alonagetzler** [comment]
note that this story should be communicated as a functionality we removed and raised in the "things to look for" discussion prior to 7.2 release

**Comment by TomerAdmon** [comment]
We still don't have a "cleanup" function, so the only way for a customer currently  to implement a cleanup is using those  attributes...  
removed the 7.2 label.

**Comment by alexazarh** [comment]
@TomerAdmon 
The idea here was to remove this attributes so that the deployed apps will always be deleted (default behavior is to delete the app if the attribute doesnt exist) and you will not be able to have an active deployed app after the reservation has ended.
I dont understand the "cleanup" function note?
